name: "Deploying a CI/CD for dotnet core web application using GitHub Actions and storing the application artifacts to Amazon S3"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v3
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
        include-prerelease: True
        
    - name: Print dotnet version
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore
      
    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build --configuration Release  
    - name: Publish the artifacts
      run: dotnet publish -c Release -o ./myapp

    - name: Zip the dotnet build
      shell: powershell
      run: Compress-Archive -Path "D:\a\mywebapp\mywebapp\myapp\" -DestinationPath "D:\a\mywebapp\mywebapp\myapp\myapp.zip"
        
    # Push artifacts to S3 bucket
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Retrieve Commit SHA for the build
      shell: powershell
      run: |
        $output = git rev-parse --short=4 HEAD
        echo $output
        echo $output > commit_sha.txt
           
    - name: Uploading the application artifacts to Amazon S3
      shell: cmd
      run: |
        aws s3 cp D:\a\mywebapp\mywebapp\myapp\myapp.zip s3://dotnet-cicd-bucket-demo/dotnet-web-app/
        aws s3 cp commit_sha.txt s3://dotnet-cicd-bucket-demo/dotnet-web-app/

        
  deploy:
    needs: build
    runs-on: [ self-hosted, Windows, X64, dotnet-core-web ]
    timeout-minutes: 10
    defaults:
      run:
        shell: cmd

    steps:
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Download the zip file from S3 to EC2 folder
      shell: powershell
      run: aws s3 cp s3://dotnet-cicd-bucket-demo/dotnet-web-app/myapp.zip C:\actions-runner\_work
        
    - name: Unzipping the Zip file
      shell: powershell
      run: Expand-Archive -Path C:\actions-runner\_work\myapp.zip -DestinationPath C:\actions-runner\_work\output

    - name: Stop IIS Server
      shell: powershell
      run: iisreset /stop       

    - name: Delete the IIS folder
      shell: powershell
      run: Remove-Item "C:\inetpub\wwwroot\*"  -Recurse
      
    - name: Copy files to wwwroot folder of IIS server
      shell: powershell
      run: Copy-Item -Path C:\actions-runner\_work\output\* -Destination "C:\inetpub\wwwroot" -Recurse -Force

    - name: Start IIS Server
      shell: powershell
      run: iisreset /start

    - name: Download the Commit SHA file from S3 bucket to EC2 location and rename the artifacts file in S3 bucket
      shell: powershell
      run: |
        aws s3 cp s3://dotnet-cicd-bucket-demo/dotnet-web-app/commit_sha.txt C:\actions-runner\_work
        $output = cat C:\actions-runner\_work\commit_sha.txt
        aws s3 mv s3://dotnet-cicd-bucket-demo/dotnet-web-app/myapp.zip s3://dotnet-cicd-bucket-demo/dotnet-web-app/myapp-$output.zip
                
    - name: Delete the unzipped output folder & zipped file to allow new builds gracefully
      shell: powershell
      run: |
        Remove-Item C:\actions-runner\_work\output -Recurse
        Remove-Item C:\actions-runner\_work\myapp.zip
            
    - name: Delete the Commit SHA file from S3 bucket and EC2 instance location 
      shell: powershell
      run: |
        aws s3 rm s3://dotnet-cicd-bucket-demo/dotnet-web-app/commit_sha.txt    
        Remove-Item C:\actions-runner\_work\commit_sha.txt
