name: "Deploying a CI/CD for .NET sample app using GitHub Actions"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [ self-hosted, Windows, X64 ]
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
        include-prerelease: True
    - name: Print dotnet version
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore
    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Publish the artifacts
      run: |
        dotnet publish -c Release -o ./myapp
    # Push artifacts to S3 bucket
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Pushing the application artifacts to Amazon S3
      uses: hkusu/s3-upload-action@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        aws-bucket: ${{ secrets.AWS_BUCKET_NAME }}
        file-path: './myapp'
    # IIS Deployment
    - name: Deploy to IIS Server
      shell: powershell
      run: |
        Start-Process powershell -ArgumentList "iisreset /stop" -Verb RunAs
        Copy-Item ./myapp/* C:/inetpub/wwwroot/ -Recurse -Force
        # Start-Process powershell -ArgumentList "Copy-Item ./myapp/* C:/inetpub/wwwroot/ -Recurse -Force" -Verb RunAs
        Start-Process powershell -ArgumentList "iisreset /start" -Verb RunAs
    - name: Curl the website 
      run: curl http://localhost/
    #   shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
    #   run: |
    #     set PATH=C:\actions-runner\_work\_temp
    #     iisreset /stop
    # - name: Curl the website as a smoke test
    #   run: curl http://localhost/

    # - name: Run Web Test
    #   run: |
    #     dotnet build --configuration Release .\dotnet-core-webapp.webtest
    #     cd .\dotnet-core-webapp.webtests
    #     dotnet test
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    # - name: Run the WebApp
    #   run: dotnet watch
