name: "Deploying a CI/CD for .NET sample app using GitHub Actions"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_ROOT: ${{ secrets.DOTNET_ROOT }}
  AWS_REGION: "us-east-1"

jobs:
  build:

    runs-on: [ self-hosted, Windows, X64 ]
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
        include-prerelease: True
    - name: Display dotnet version
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore
    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: dotnet app publish
      shell: cmd
      run: |
        dotnet publish -c Release -o "$DOTNET_ROOT/mywebapp"
    # IIS Deployment
    - name: Run Powershell Commands
      shell: powershell
      run: echo "Hello world"
    - name: Stop IIS
      shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
      run: iisreset /stop
    # - name: Curl the website as a smoke test
    #   run: curl http://localhost/

    # - name: Run Web Test
    #   run: |
    #     dotnet build --configuration Release .\dotnet-core-webapp.webtest
    #     cd .\dotnet-core-webapp.webtests
    #     dotnet test
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    # - name: Run the WebApp
    #   run: dotnet watch
